### ISSUE TITLE
The code works, transcribes and fetches the response but throws error as well

### ISSUE THREAD

**Issue by priyanka22kar** [skapadia3214/groq-voice#1]
audio_stream = self.text_to_speech(response_text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    for chunk in response:
  File "\Lib\site-packages\elevenlabs\text_to_speech\client.py", line 189, in convert
    raise ApiError(status_code=_response.status_code, body=_response_json)
elevenlabs.core.api_error.ApiError: status_code: 400, body: {'detail': {'status': 'voice_not_found', 'message': 'A voice for the voice_id 876MHA6EtWKaHTEGz was not found.'}}

**Comment by skapadia3214** [comment]
Changed default eleven labs voice back to Adam. If you want to use different voices you will need to add it through the [voice lab](https://elevenlabs.io/app/voice-lab)
